/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Model.ChiTietCaThi;
import Model.MonThi;
import Table.TableSinhVien;
import Model.SinhVien;
import Model.SinhVienXem;
import Model.ToChucThi;
import Table.TableSinhVienXem;
import Utils.File;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author admin
 */
public class SinhVienXemLichThi extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySinhVien
     */
    ArrayList<SinhVienXem> dsSinhVien = new ArrayList<SinhVienXem>();
    ArrayList<ChiTietCaThi> dsChiTiet = new ArrayList<ChiTietCaThi>();
    ArrayList<ToChucThi> dsToChuc = new ArrayList<ToChucThi>();
    int dongchon = -1;
    
    SinhVienXem sinhvien = new SinhVienXem();
    ChiTietCaThi chitiet =new ChiTietCaThi();
    ToChucThi tochuc =new ToChucThi();
    public SinhVienXemLichThi() {
        initComponents();
        LoadTableFromFile();
        LoadTableSinhVien();
        indexComboBox();
    }
    
    void LoadTableFromFile(){
        File f1 = new File("danhSachChiTietCaThi.txt");
        File f2 = new File("danhSachToChucThi.txt");
        
        ArrayList<String> listct = f1.ReadFromFile();
        ArrayList<String> listtc = f2.ReadFromFile();
        
        for(String s : listct){
            String[] txt = s.split(",");
            chitiet = new ChiTietCaThi(txt[0],txt[1],txt[2],txt[3]);
            dsChiTiet.add(chitiet);
        }
        for(String s : listtc){
            String[] txt = s.split(",");
            tochuc = new ToChucThi(txt[0],txt[1],txt[2],txt[3],txt[4]);
            dsToChuc.add(tochuc);
        }
    }
    
    public void LoadTableSinhVien(){
       jTableQuanLySinhVien.setModel(new TableSinhVienXem(sinhvien));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQuanLySinhVien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbMaSV = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextTenSV = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("SINH VIÊN");

        jTableQuanLySinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "Môn Thi", "Phòng Thi", "Thời Gian"
            }
        ));
        jTableQuanLySinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQuanLySinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableQuanLySinhVien);

        jLabel2.setText("Mã SV:");

        cbMaSV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaSVActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonThoat)
                                .addGap(220, 220, 220)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jTextTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThoat)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableQuanLySinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQuanLySinhVienMouseClicked

    }//GEN-LAST:event_jTableQuanLySinhVienMouseClicked

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        int ret=JOptionPane.showConfirmDialog(null,
                "bạn chắc chắn muốn thoát?", "Thoát",
                JOptionPane.YES_NO_OPTION);
        if(ret==JOptionPane.YES_OPTION){
            new Login().setVisible(true);
            this.setVisible(false);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void cbMaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaSVActionPerformed
        // TODO add your handling code here:
        
        try{
                    for(ChiTietCaThi i :dsChiTiet)
                        {
                            if(cbMaSV.getSelectedItem()==null){
                                jTextTenSV.setText("");
                            }
                            else if((i.getMasv()).equals(cbMaSV.getSelectedItem().toString()))
                            {
                                jTextTenSV.setText(i.getTensv());
                            }
                        }
            String masv=cbMaSV.getSelectedItem().toString();
            String tensv=jTextTenSV.getText().toString();
            sinhvien = new SinhVienXem(masv,tensv,tochuc.getMonthi().toString(),tochuc.getPhongthi().toString(),tochuc.getThoigianthi().toString(),chitiet.getSbd().toString() );
            
            LoadTableSinhVien();
        }catch(Exception e){
            //JOptionPane.showMessageDialog(rootPane, e.getMessage());
            System.out.println("CanhBao");
        }
    }//GEN-LAST:event_cbMaSVActionPerformed

    void indexComboBox(){
        cbMaSV.removeAllItems();
        for(ChiTietCaThi i :dsChiTiet){
            cbMaSV.addItem(i.getMasv());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienXemLichThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienXemLichThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienXemLichThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienXemLichThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienXemLichThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbMaSV;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableQuanLySinhVien;
    private javax.swing.JTextField jTextTenSV;
    // End of variables declaration//GEN-END:variables
}
